language: cpp
compiler: gcc
dist: xenial
sudo: required
notifications:
  email:
    recipients:
      - mchehab@kernel.org
    on_success: change
    on_failure: always
cache:
  directories:
    - $HOME/.ccache
    - $HOME/pbuilder-bases
matrix:
  fast_finish: true
  include:
    - os: windows
      cache: false
      env: TARGET_OS=pc DIRECT_SHOW="--with-directshow"
before_install:
  - "${TRAVIS_BUILD_DIR}/travis/${TRAVIS_OS_NAME}.${TARGET_OS}.before_install"
install:
  - "${TRAVIS_BUILD_DIR}/travis/${TRAVIS_OS_NAME}.${TARGET_OS}.install"
script:
  - "${TRAVIS_BUILD_DIR}/travis/${TRAVIS_OS_NAME}.${TARGET_OS}.script"
after_script:
  - ps aux
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then ccache -s; fi
